/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package swingmodel;

import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Point;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.net.URL;
import javax.swing.ImageIcon;
import model.Jatek;

/**
 *
 * @author Roland
 */
public final class Ajto extends javax.swing.JPanel {
    private byte szam;
    private Jatek jatek;
    /**
     * Creates new form Ajto
     * @param jatek
     * @param szam
     * @param x
     * @param y
     */
    public Ajto(Jatek jatek, byte szam, int x, int y) {
        setJatek(jatek);
        this.szam = szam;
        initComponents();
        setSize(new Dimension(162, 308));
        setLocation(new Point(x, y));
        setVisible(true);
    }
    
    public void kinyit(boolean kincs){
        URL zarva = Ajto.class.getClassLoader().getResource("resources/kecsketrue.jpg");
        URL nyitva = Ajto.class.getClassLoader().getResource("resources/auto.png");
        Image resized = getScaledImage(new ImageIcon(kincs ? nyitva : zarva)
                .getImage(), La_kep.getWidth(), La_kep.getHeight());
        La_kep.setIcon(new ImageIcon(resized));
        Bt_valaszt.setEnabled(false);
    }
    
    public void bezar(){
        URL ajto = Ajto.class.getClassLoader().getResource("resources/faajto.png");
        Image resized = getScaledImage(new ImageIcon(ajto)
                .getImage(), La_kep.getWidth(), La_kep.getHeight());
        La_kep.setIcon(new ImageIcon(resized));
        Bt_valaszt.setEnabled(true);
    }
    
    public void setJatek(Jatek jatek){
        this.jatek = jatek;
    }
    
    private Image getScaledImage(Image srcImg, int w, int h){
        BufferedImage resizedImg = new BufferedImage(w, h, BufferedImage.TYPE_INT_ARGB);
        Graphics2D g2 = resizedImg.createGraphics();
        g2.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
        g2.drawImage(srcImg, 0, 0, w, h, null);
        g2.dispose();
        return resizedImg;
    }
    
    public int getSzam(){
        return szam;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        La_kep = new javax.swing.JLabel();
        Bt_valaszt = new javax.swing.JButton();

        jLabel2.setBackground(new java.awt.Color(255, 51, 51));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/faajto.png"))); // NOI18N
        jLabel2.setOpaque(true);

        jButton2.setText("jButton1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setMaximumSize(new java.awt.Dimension(162, 308));
        setMinimumSize(new java.awt.Dimension(162, 308));

        La_kep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/faajto.png"))); // NOI18N
        La_kep.setOpaque(true);

        Bt_valaszt.setText("választ");
        Bt_valaszt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_valasztActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(La_kep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(Bt_valaszt, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(La_kep)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Bt_valaszt)
                .addGap(3, 3, 3))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Bt_valasztActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_valasztActionPerformed
        jatek.valaszt(szam);
    }//GEN-LAST:event_Bt_valasztActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bt_valaszt;
    private javax.swing.JLabel La_kep;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
